// app/components/profile/ProfileContractInfo.vue
<script setup lang="ts">
/**
 * ProfileContractInfo — информация о договоре
 *
 * Отображает номер договора, статус, тариф и дату заключения.
 */
import { formatDate } from '~/composables/useFormatters'

// =============================================================================
// STORES & COMPOSABLES
// =============================================================================

const accountStore = useAccountStore()
</script>

<template>
  <UiCard>
    <div class="flex items-center justify-between mb-3 md:mb-5">
      <h2 class="text-base md:text-lg font-semibold text-[var(--text-primary)]">Договор</h2>
    </div>

    <div class="space-y-2 md:space-y-4">
      <div class="flex items-center justify-between py-2 md:py-3" style="border-bottom: 1px solid var(--glass-border);">
        <span class="text-xs md:text-sm text-[var(--text-muted)]">Номер договора</span>
        <span class="text-xs md:text-base text-[var(--text-primary)] font-medium">{{ accountStore.account?.contractNumber }}</span>
      </div>
      <div class="flex items-center justify-between py-2 md:py-3" style="border-bottom: 1px solid var(--glass-border);">
        <span class="text-xs md:text-sm text-[var(--text-muted)]">Статус</span>
        <UiBadge :variant="accountStore.isBlocked ? 'danger' : 'success'" class="text-[10px] md:text-xs">
          {{ accountStore.isBlocked ? 'Приостановлен' : 'Активен' }}
        </UiBadge>
      </div>
      <div class="flex items-center justify-between py-2 md:py-3" style="border-bottom: 1px solid var(--glass-border);">
        <span class="text-xs md:text-sm text-[var(--text-muted)]">Тариф</span>
        <span class="text-xs md:text-base text-[var(--text-primary)]">{{ accountStore.account?.tariff || 'Не подключен' }}</span>
      </div>
      <div class="flex items-center justify-between py-2 md:py-3">
        <span class="text-xs md:text-sm text-[var(--text-muted)]">Дата заключения</span>
        <span class="text-xs md:text-base text-[var(--text-primary)]">{{ formatDate(accountStore.account?.startDate || '') || '—' }}</span>
      </div>
    </div>
  </UiCard>
</template>

// src/components/profile/profile-contract-info.tsx
'use client'

import { UiCard } from '@/components/ui/ui-card'
import { useAccountStore, isBlocked } from '@/store/use-account-store'
import { formatDate } from '@/lib/formatters'

export function ProfileContractInfo() {
  const account = useAccountStore((s) => s.account)
  const blocked = isBlocked(account)

  return (
    <UiCard>
      <h2 className="mb-3 text-base font-semibold text-[var(--text-primary)] md:mb-5 md:text-lg">
        Договор
      </h2>
      <div className="space-y-2 md:space-y-4">
        <div
          className="flex items-center justify-between py-2 md:py-3"
          style={{ borderBottom: '1px solid var(--glass-border)' }}
        >
          <span className="text-xs text-[var(--text-muted)] md:text-sm">Номер договора</span>
          <span className="text-xs font-medium text-[var(--text-primary)] md:text-base">
            {account?.contractNumber ?? '—'}
          </span>
        </div>
        <div
          className="flex items-center justify-between py-2 md:py-3"
          style={{ borderBottom: '1px solid var(--glass-border)' }}
        >
          <span className="text-xs text-[var(--text-muted)] md:text-sm">Статус</span>
          <span
            className={`rounded px-2 py-0.5 text-[10px] md:text-xs ${
              blocked ? 'bg-red-500/20 text-red-400' : 'bg-accent/20 text-accent'
            }`}
          >
            {blocked ? 'Приостановлен' : 'Активен'}
          </span>
        </div>
        <div
          className="flex items-center justify-between py-2 md:py-3"
          style={{ borderBottom: '1px solid var(--glass-border)' }}
        >
          <span className="text-xs text-[var(--text-muted)] md:text-sm">Тариф</span>
          <span className="text-xs text-[var(--text-primary)] md:text-base">
            {account?.tariff || 'Не подключен'}
          </span>
        </div>
        <div className="flex items-center justify-between py-2 md:py-3">
          <span className="text-xs text-[var(--text-muted)] md:text-sm">Дата заключения</span>
          <span className="text-xs text-[var(--text-primary)] md:text-base">
            {account?.startDate ? formatDate(account.startDate) : '—'}
          </span>
        </div>
      </div>
    </UiCard>
  )
}
