// src/app/(dashboard)/invoices/page.tsx
'use client'

import { useState, useMemo } from 'react'
import { UiCard } from '@/components/ui/ui-card'
import { UiButton } from '@/components/ui/ui-button'
import {
  type Invoice,
  type InvoiceStatus,
  formatInvoicePeriod,
  invoiceStatusLabels,
  invoiceStatusColors,
} from '@/types/invoice'
import { formatKopeks, formatDateShort } from '@/lib/formatters'
import { mockInvoiceDetails } from '@/lib/mock-invoice-details'

const UNPAID_STATUSES: InvoiceStatus[] = ['pending', 'sent', 'viewed', 'expired']

function getMonthDates(year: number, month: number) {
  const start = new Date(year, month - 1, 1)
  const end = new Date(year, month, 0)
  return {
    start: start.toISOString().split('T')[0] ?? null,
    end: end.toISOString().split('T')[0] ?? null,
  }
}

function generateMockInvoices(): Invoice[] {
  const now = new Date()
  const currentYear = now.getFullYear()
  const currentMonth = now.getMonth() + 1
  const list: Invoice[] = []

  const nextMonth = currentMonth === 12 ? 1 : currentMonth + 1
  const nextYear = currentMonth === 12 ? currentYear + 1 : currentYear
  const nextDates = getMonthDates(nextYear, nextMonth)

  list.push({
    id: `mock-invoice-${nextYear}-${String(nextMonth).padStart(2, '0')}`,
    invoiceNumber: `INV-${nextYear}${String(nextMonth).padStart(2, '0')}-001`,
    accountId: 'mock-account-id',
    contractId: null,
    status: 'pending',
    amount: mockInvoiceDetails.totalToPay,
    description: 'Ежемесячная плата за интернет',
    periodStart: nextDates.start,
    periodEnd: nextDates.end,
    issuedAt: new Date(nextYear, nextMonth - 1, 1).toISOString(),
    dueDate: new Date(nextYear, nextMonth, 0).toISOString(),
    paidAt: null,
    createdAt: new Date(nextYear, nextMonth - 1, 1).toISOString(),
    updatedAt: new Date(nextYear, nextMonth - 1, 1).toISOString(),
  })

  for (let i = 0; i < 9; i++) {
    let month = currentMonth - i - 1
    let year = currentYear
    while (month <= 0) {
      month += 12
      year -= 1
    }
    const monthDates = getMonthDates(year, month)
    const paidDate = new Date(year, month - 1, 10 + (i % 20))
    list.push({
      id: `mock-invoice-${year}-${String(month).padStart(2, '0')}`,
      invoiceNumber: `INV-${year}${String(month).padStart(2, '0')}-001`,
      accountId: 'mock-account-id',
      contractId: null,
      status: 'paid',
      amount: mockInvoiceDetails.totalToPay,
      description: 'Ежемесячная плата за интернет',
      periodStart: monthDates.start,
      periodEnd: monthDates.end,
      issuedAt: new Date(year, month - 1, 1).toISOString(),
      dueDate: new Date(year, month, 0).toISOString(),
      paidAt: paidDate.toISOString(),
      createdAt: new Date(year, month - 1, 1).toISOString(),
      updatedAt: paidDate.toISOString(),
    })
  }
  return list
}

function getStatusBadgeClass(status: InvoiceStatus): string {
  if (UNPAID_STATUSES.includes(status)) return 'bg-red-500/20 text-red-400'
  const map: Record<string, string> = {
    gray: 'bg-gray-600/20 text-gray-400',
    primary: 'bg-primary/20 text-primary',
    blue: 'bg-blue-500/20 text-blue-400',
    green: 'bg-accent/20 text-accent',
    red: 'bg-red-500/20 text-red-400',
  }
  return map[invoiceStatusColors[status]] ?? map.gray
}

function DocumentIcon({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
    </svg>
  )
}
function CheckIcon({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  )
}
function ChevronRightIcon({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
    </svg>
  )
}
function CloseIcon({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
    </svg>
  )
}

const filters = [
  { value: 'all' as const, label: 'Все' },
  { value: 'unpaid' as const, label: 'К оплате' },
  { value: 'paid' as const, label: 'Оплаченные' },
]

export default function InvoicesPage() {
  const [invoices] = useState<Invoice[]>(() => generateMockInvoices())
  const [filter, setFilter] = useState<'all' | 'unpaid' | 'paid'>('all')
  const [servicesModalInvoice, setServicesModalInvoice] = useState<Invoice | null>(null)

  const filteredInvoices = useMemo(() => {
    if (filter === 'unpaid') return invoices.filter((inv) => UNPAID_STATUSES.includes(inv.status))
    if (filter === 'paid') return invoices.filter((inv) => inv.status === 'paid')
    return invoices
  }, [invoices, filter])

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-[var(--text-primary)]">Счета</h1>
        <p className="mt-1 text-[var(--text-muted)]">История выставленных счетов</p>
      </div>

      <div className="flex gap-2">
        {filters.map((f) => (
          <button
            key={f.value}
            type="button"
            onClick={() => setFilter(f.value)}
            className={`rounded-lg px-4 py-2 text-sm font-medium transition-colors ${
              filter === f.value ? 'bg-primary text-white' : 'text-[var(--text-muted)] hover:text-[var(--text-primary)]'
            }`}
            style={filter !== f.value ? { background: 'var(--glass-bg)' } : undefined}
          >
            {f.label}
          </button>
        ))}
      </div>

      <div className="space-y-4">
        {filteredInvoices.map((invoice) => (
          <UiCard
            key={invoice.id}
            hover
            className="cursor-pointer"
            onClick={() => setServicesModalInvoice(invoice)}
          >
            <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
              <div className="flex items-start gap-4">
                <div className="flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-primary/20 to-secondary/10">
                  {invoice.status === 'paid' ? (
                    <CheckIcon className="h-6 w-6 text-accent" />
                  ) : (
                    <DocumentIcon className="h-6 w-6 text-primary" />
                  )}
                </div>
                <div>
                  <div className="mb-1 flex items-center gap-2">
                    <span className="text-xs text-[var(--text-muted)]">{invoice.invoiceNumber}</span>
                    <span
                      className={`rounded px-2 py-0.5 text-xs font-medium ${getStatusBadgeClass(invoice.status)}`}
                    >
                      {invoiceStatusLabels[invoice.status]}
                    </span>
                  </div>
                  <p className="font-medium text-[var(--text-primary)]">{formatInvoicePeriod(invoice)}</p>
                  <div className="mt-2 flex items-center gap-3 text-xs text-[var(--text-muted)]">
                    {invoice.issuedAt && <span>Выставлен: {formatDateShort(invoice.issuedAt)}</span>}
                    {invoice.paidAt && <span>Оплачен: {formatDateShort(invoice.paidAt)}</span>}
                    {!invoice.paidAt && invoice.dueDate && (
                      <span>Срок: {formatDateShort(invoice.dueDate)}</span>
                    )}
                  </div>
                </div>
              </div>
              <div className="flex items-center gap-4">
                <span className="text-lg font-bold text-[var(--text-primary)]">
                  {formatKopeks(invoice.amount)}
                  <span className="text-sm font-normal text-[var(--text-muted)]"> ₽</span>
                </span>
                <ChevronRightIcon className="h-5 w-5 text-[var(--text-muted)]" />
              </div>
            </div>
          </UiCard>
        ))}

        {filteredInvoices.length === 0 && (
          <UiCard padding="lg">
            <p className="text-center text-[var(--text-muted)]">Счетов не найдено</p>
          </UiCard>
        )}
      </div>

      {servicesModalInvoice && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm"
          onClick={() => setServicesModalInvoice(null)}
        >
          <div
            className="relative max-h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl"
            style={{
              background: 'var(--bg-surface)',
              border: '1px solid var(--glass-border)',
              boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <div
              className="flex items-center justify-between border-b p-6"
              style={{ borderColor: 'var(--glass-border)' }}
            >
              <div>
                <h2 className="text-xl font-bold text-[var(--text-primary)]">Состав услуг</h2>
                <p className="mt-1 text-sm text-[var(--text-muted)]">
                  {servicesModalInvoice.invoiceNumber} • {formatInvoicePeriod(servicesModalInvoice)}
                </p>
              </div>
              <button
                type="button"
                onClick={() => setServicesModalInvoice(null)}
                className="rounded-lg p-2 transition-colors hover:bg-[var(--glass-bg)]"
              >
                <CloseIcon className="h-5 w-5 text-[var(--text-muted)]" />
              </button>
            </div>
            <div className="max-h-[60vh] overflow-y-auto p-6">
              <div className="space-y-6">
                {mockInvoiceDetails.addresses.map((addr, idx) => (
                  <div key={idx} className="space-y-4">
                    <div
                      className="rounded-xl border-l-4 border-primary bg-gradient-to-r from-primary/10 to-secondary/5 p-4"
                    >
                      <p className="text-sm font-semibold leading-relaxed text-[var(--text-primary)]">
                        {addr.address}
                      </p>
                    </div>
                    <div className="space-y-2 pl-4">
                      {addr.services.map((svc, sidx) => (
                        <div
                          key={sidx}
                          className="flex items-start justify-between gap-4 rounded-lg p-4"
                          style={{
                            background: 'var(--glass-bg)',
                            borderBottom:
                              sidx < addr.services.length - 1 ? '1px solid var(--glass-border)' : undefined,
                          }}
                        >
                          <p className="text-sm text-[var(--text-primary)]">{svc.name}</p>
                          <span className="text-base font-bold whitespace-nowrap text-[var(--text-primary)]">
                            {formatKopeks(svc.price)} ₽
                          </span>
                        </div>
                      ))}
                      <div
                        className="mt-3 flex items-center justify-between gap-4 rounded-lg border-2 p-4"
                        style={{ borderColor: 'var(--glass-border)' }}
                      >
                        <span className="text-sm font-semibold text-[var(--text-primary)]">
                          Итого по адресу:
                        </span>
                        <span className="text-lg font-bold text-primary whitespace-nowrap">
                          {formatKopeks(addr.services.reduce((s, x) => s + x.price, 0))} ₽
                        </span>
                      </div>
                    </div>
                  </div>
                ))}
                <div
                  className="border-t-2 pt-6"
                  style={{ borderColor: 'var(--glass-border)' }}
                >
                  <div className="space-y-3">
                    <div className="flex justify-between rounded-lg p-3" style={{ background: 'var(--glass-bg)' }}>
                      <span className="text-sm text-[var(--text-muted)]">Сумма услуг:</span>
                      <span className="font-semibold text-[var(--text-primary)]">
                        {formatKopeks(mockInvoiceDetails.totalAmount)} ₽
                      </span>
                    </div>
                    <div className="flex justify-between rounded-lg p-3" style={{ background: 'var(--glass-bg)' }}>
                      <span className="text-sm text-[var(--text-muted)]">Баланс счета:</span>
                      <span className="font-semibold text-[var(--text-primary)]">
                        {formatKopeks(mockInvoiceDetails.balance)} ₽
                      </span>
                    </div>
                    <div
                      className="mt-2 flex justify-between rounded-lg border-2 p-4"
                      style={{ borderColor: 'var(--glass-border)' }}
                    >
                      <span className="font-bold text-[var(--text-primary)]">Итого к оплате:</span>
                      <span className="text-xl font-bold text-primary">
                        {formatKopeks(mockInvoiceDetails.totalToPay)} ₽
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {UNPAID_STATUSES.includes(servicesModalInvoice.status) && (
              <div
                className="border-t p-6"
                style={{ borderColor: 'var(--glass-border)', background: 'var(--bg-surface)' }}
              >
                <UiButton
                  variant="primary"
                  className="w-full sm:w-auto"
                  onClick={() => window.open('https://invoice.doka.team/', '_blank')}
                >
                  Счет на оплату
                </UiButton>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

// app/pages/invoices/index.vue
<script setup lang="ts">
/**
 * Страница счетов — история выставленных счетов:
 * - Фильтрация: все / к оплате / оплаченные
 * - Клик по счёту открывает детальную страницу
 *
 * Статусы счетов:
 * - pending, sent, viewed — неоплаченные
 * - paid — оплаченный
 * - expired — просроченный
 */
import type { Invoice, InvoiceStatus } from '~/types/invoice'
import { invoiceStatusLabels, invoiceStatusColors } from '~/types/invoice'
import { formatKopeks, formatDateShort } from '~/composables/useFormatters'

definePageMeta({
  middleware: 'auth'
})

// =============================================================================
// DATA — счета из API
// =============================================================================

const invoices = ref<Invoice[]>([])
const pending = ref(false)
const error = ref<string | null>(null)

async function loadInvoices() {
  pending.value = true
  error.value = null
  try {
    const data = await $fetch<{ invoices: Invoice[] }>('/api/invoices')
    invoices.value = data.invoices ?? []
  } catch (e: unknown) {
    const err = e as { data?: { message?: string } }
    error.value = err.data?.message || 'Не удалось загрузить счета'
    invoices.value = []
  } finally {
    pending.value = false
  }
}

function refresh() {
  loadInvoices()
}

// =============================================================================
// STATE — фильтр
// =============================================================================

const filter = ref<'all' | 'unpaid' | 'paid'>('all')
const route = useRoute()

onMounted(async () => {
  await loadInvoices()

  const filterParam = route.query.filter as string
  if (filterParam && ['all', 'unpaid', 'paid'].includes(filterParam)) {
    filter.value = filterParam as 'all' | 'unpaid' | 'paid'
  }
})

// =============================================================================
// COMPUTED
// =============================================================================

const filteredInvoices = computed(() => {
  if (filter.value === 'unpaid') {
    return invoices.value.filter(inv => unpaidStatuses.includes(inv.status))
  }
  if (filter.value === 'paid') {
    return invoices.value.filter(inv => inv.status === 'paid')
  }
  return invoices.value
})

// =============================================================================
// CONSTANTS
// =============================================================================

const unpaidStatuses = ['pending', 'sent', 'viewed', 'expired']

const filters = [
  { value: 'all', label: 'Все' },
  { value: 'unpaid', label: 'К оплате' },
  { value: 'paid', label: 'Оплаченные' }
]

// =============================================================================
// METHODS
// =============================================================================

function getStatusBadgeClass(status: InvoiceStatus): string {
  const unpaidStatuses = ['pending', 'sent', 'viewed', 'expired']
  if (unpaidStatuses.includes(status)) {
    return 'bg-red-500/20 text-red-400'
  }

  const colorMap: Record<string, string> = {
    gray: 'bg-gray-600/20 text-gray-400',
    primary: 'bg-primary/20 text-primary',
    blue: 'bg-blue-500/20 text-blue-400',
    green: 'bg-accent/20 text-accent',
    red: 'bg-red-500/20 text-red-400'
  }
  const color = invoiceStatusColors[status] as string
  return (color in colorMap ? colorMap[color] : colorMap.gray) as string
}
</script>

<template>
  <div class="invoices-page space-y-8">
    <!-- PAGE HEADER -->
    <div>
      <h1 class="text-2xl font-bold text-[var(--text-primary)]">Счета</h1>
      <p class="text-[var(--text-muted)] mt-1">История выставленных счетов и управление оплатами</p>
    </div>

    <!-- FILTERS -->
    <div class="flex flex-wrap gap-2 p-1 rounded-2xl" style="background: var(--glass-bg); border: 1px solid var(--glass-border); width: fit-content;">
      <button
        v-for="f in filters"
        :key="f.value"
        @click="filter = f.value as any"
        class="invoices-page__filter px-5 py-2.5 rounded-xl text-sm font-semibold transition-all duration-300"
        :class="filter === f.value
          ? 'bg-primary text-white shadow-lg shadow-primary/25'
          : 'text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-[var(--glass-hover-bg)]'"
      >
        {{ f.label }}
      </button>
    </div>

    <!-- LOADING -->
    <div v-if="pending" class="space-y-4">
      <UiCard v-for="i in 3" :key="i" class="animate-pulse">
        <div class="flex items-center gap-4">
          <div class="w-12 h-12 rounded-xl bg-[var(--glass-bg)]"></div>
          <div class="flex-1 space-y-2">
            <div class="h-4 bg-[var(--glass-bg)] rounded w-1/3"></div>
            <div class="h-3 bg-[var(--glass-bg)] rounded w-1/2"></div>
          </div>
        </div>
      </UiCard>
    </div>

    <!-- ERROR -->
    <UiCard v-else-if="error">
      <UiErrorState
        title="Ошибка загрузки"
        description="Не удалось загрузить счета"
        @retry="refresh"
      />
    </UiCard>

    <!-- INVOICES TABLE (desktop) + CARDS (mobile) -->
    <div v-else>
      <UiCard v-if="filteredInvoices.length === 0" padding="lg">
        <UiEmptyState
          icon="heroicons:document-text"
          title="Счетов не найдено"
        />
      </UiCard>

      <template v-else>
        <!-- Desktop: таблица -->
        <div class="invoices-list animate-fade-in hidden md:block">
          <div class="invoices-list__header">
            <div class="invoices-col invoices-col--status">Статус</div>
            <div class="invoices-col invoices-col--date">Дата выставления</div>
            <div class="invoices-col invoices-col--date">Оплачен / Срок</div>
            <div class="invoices-col invoices-col--amount">Сумма</div>
            <div class="invoices-col invoices-col--actions">Действия</div>
          </div>

          <div class="invoices-list__body">
            <div
              v-for="invoice in filteredInvoices"
              :key="invoice.id"
              :id="`invoice-${invoice.id}`"
              class="invoices-row group"
              @click="navigateTo(`/invoices/${invoice.id}`)"
            >
              <div class="invoices-col invoices-col--status">
                <span
                  class="invoices-row__badge"
                  :class="invoice.status === 'paid' ? 'invoices-row__badge--paid' : 'invoices-row__badge--unpaid'"
                >
                  <Icon
                    :name="invoice.status === 'paid' ? 'heroicons:check-circle' : 'heroicons:clock'"
                    class="w-4 h-4"
                  />
                  {{ invoiceStatusLabels[invoice.status] }}
                </span>
              </div>
              <div class="invoices-col invoices-col--date">
                <span class="text-[var(--text-secondary)]">
                  {{ invoice.issuedAt ? formatDateShort(invoice.issuedAt) : '—' }}
                </span>
              </div>
              <div class="invoices-col invoices-col--date">
                <span class="text-[var(--text-secondary)]">
                  {{ invoice.paidAt ? formatDateShort(invoice.paidAt) : (invoice.dueDate ? formatDateShort(invoice.dueDate) : '—') }}
                </span>
              </div>
              <div class="invoices-col invoices-col--amount">
                <span class="invoices-row__amount">
                  {{ formatKopeks(invoice.amount) }}<span class="invoices-row__currency">₽</span>
                </span>
              </div>
              <div class="invoices-col invoices-col--actions">
                <NuxtLink
                  v-if="!unpaidStatuses.includes(invoice.status)"
                  :to="`/invoices/${invoice.id}`"
                >
                  <UiButton variant="ghost" size="sm">
                    Подробнее
                    <Icon name="heroicons:chevron-right" class="w-4 h-4" />
                  </UiButton>
                </NuxtLink>
                <NuxtLink
                  v-if="unpaidStatuses.includes(invoice.status)"
                  :to="`/invoices/${invoice.id}`"
                >
                  <UiButton variant="primary" size="sm">
                    Оплатить
                  </UiButton>
                </NuxtLink>
              </div>
            </div>
          </div>

          <div class="invoices-list__count">
            Всего: <strong class="text-[var(--text-primary)]">{{ filteredInvoices.length }}</strong> счетов
          </div>
        </div>

        <!-- Mobile: карточки -->
        <div class="md:hidden animate-fade-in space-y-3">
          <div
            v-for="invoice in filteredInvoices"
            :key="invoice.id"
            :id="`invoice-${invoice.id}`"
            class="invoices-mobile"
            @click="navigateTo(`/invoices/${invoice.id}`)"
          >
            <div class="invoices-mobile__top">
              <span
                class="invoices-row__badge"
                :class="invoice.status === 'paid' ? 'invoices-row__badge--paid' : 'invoices-row__badge--unpaid'"
              >
                <Icon
                  :name="invoice.status === 'paid' ? 'heroicons:check-circle' : 'heroicons:clock'"
                  class="w-4 h-4"
                />
                {{ invoiceStatusLabels[invoice.status] }}
              </span>
            </div>

            <div class="invoices-mobile__details">
              <div class="invoices-mobile__detail">
                <span class="invoices-mobile__label">Выставлен</span>
                <span class="invoices-mobile__value">{{ invoice.issuedAt ? formatDateShort(invoice.issuedAt) : '—' }}</span>
              </div>
              <div class="invoices-mobile__detail">
                <span class="invoices-mobile__label">{{ invoice.paidAt ? 'Оплачен' : 'Срок оплаты' }}</span>
                <span class="invoices-mobile__value">
                  {{ invoice.paidAt ? formatDateShort(invoice.paidAt) : (invoice.dueDate ? formatDateShort(invoice.dueDate) : '—') }}
                </span>
              </div>
              <div class="invoices-mobile__detail invoices-mobile__detail--amount">
                <span class="invoices-mobile__label">Сумма</span>
                <span class="invoices-row__amount">
                  {{ formatKopeks(invoice.amount) }}<span class="invoices-row__currency">₽</span>
                </span>
              </div>
            </div>

            <div class="invoices-mobile__actions" @click.stop>
              <NuxtLink
                v-if="!unpaidStatuses.includes(invoice.status)"
                :to="`/invoices/${invoice.id}`"
                class="flex-1"
              >
                <UiButton variant="ghost" size="sm" block>
                  Подробнее
                  <Icon name="heroicons:chevron-right" class="w-4 h-4" />
                </UiButton>
              </NuxtLink>
              <NuxtLink
                v-if="unpaidStatuses.includes(invoice.status)"
                :to="`/invoices/${invoice.id}`"
                class="flex-shrink-0"
              >
                <UiButton variant="primary" size="sm">
                  Оплатить
                </UiButton>
              </NuxtLink>
            </div>
          </div>

          <p class="text-xs text-[var(--text-muted)] text-center pt-2">
            Всего: <strong class="text-[var(--text-primary)]">{{ filteredInvoices.length }}</strong> счетов
          </p>
        </div>
      </template>
    </div>

  </div>
</template>

<style scoped>
.invoices-list {
  border-radius: 1.25rem;
  overflow: hidden;
  background: var(--bg-surface);
  border: 1px solid var(--glass-border);
  box-shadow: 0 4px 24px var(--glass-shadow);
}

.invoices-col {
  display: flex;
  align-items: center;
  min-width: 0;
  font-size: 0.9rem;
}

.invoices-list__header,
.invoices-row {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
  gap: 0 1.5rem;
}

.invoices-list__header {
  padding: 1.875rem 1.5rem;
  border-bottom: 2px solid var(--glass-border);
}

.invoices-list__header .invoices-col {
  font-size: 0.75rem;
  font-weight: 600;
  letter-spacing: 0.05em;
  text-transform: uppercase;
  color: var(--text-muted);
  user-select: none;
}

.invoices-row {
  padding: 1rem 1.5rem;
  cursor: pointer;
  transition: background-color 0.15s ease, transform 0.15s ease, box-shadow 0.15s ease;
  border-bottom: 1px solid var(--glass-border);
  position: relative;
}

.invoices-row:last-child {
  border-bottom: none;
}

.invoices-row:hover {
  background: var(--glass-hover-bg);
  box-shadow: inset 0 0 0 1px var(--glass-hover-border);
  z-index: 1;
}

.invoices-col--amount {
  justify-content: flex-end;
  text-align: right;
}

.invoices-col--actions {
  justify-content: center;
  gap: 0.5rem;
  padding-left: 1.5rem;
}

.invoices-row__badge {
  display: inline-flex;
  align-items: center;
  gap: 0.375rem;
  padding: 0.3rem 0.75rem;
  border-radius: 999px;
  font-size: 0.8125rem;
  font-weight: 600;
  line-height: 1;
  white-space: nowrap;
}

.invoices-row__badge--paid {
  background: rgba(0, 166, 81, 0.12);
  color: #00A651;
}

.invoices-row__badge--unpaid {
  background: rgba(247, 148, 29, 0.12);
  color: #F7941D;
}

.invoices-row__amount {
  font-weight: 700;
  font-size: 0.9375rem;
  font-variant-numeric: tabular-nums;
  color: var(--text-primary);
}

.invoices-row__currency {
  margin-left: 0.2em;
  font-weight: 400;
  color: var(--text-muted);
}

.invoices-list__count {
  padding: 0.75rem 1.5rem;
  font-size: 0.75rem;
  color: var(--text-muted);
  border-top: 1px solid var(--glass-border);
}

.invoices-mobile {
  border-radius: 1rem;
  overflow: hidden;
  background: var(--bg-surface);
  border: 1px solid var(--glass-border);
  box-shadow: 0 2px 12px var(--glass-shadow);
  cursor: pointer;
  transition: box-shadow 0.2s ease, border-color 0.2s ease;
}

.invoices-mobile:active {
  box-shadow: 0 1px 4px var(--glass-shadow);
}

.invoices-mobile__top {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.875rem 1rem 0;
}

.invoices-mobile__details {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 0.5rem 0.75rem;
  padding: 0.75rem 1rem;
}

.invoices-mobile__label {
  font-size: 0.6875rem;
  font-weight: 500;
  letter-spacing: 0.02em;
  text-transform: uppercase;
  color: var(--text-muted);
  margin-bottom: 0.25rem;
}

.invoices-mobile__value {
  font-size: 0.8125rem;
  font-weight: 500;
  color: var(--text-primary);
  line-height: 1.4;
}

.invoices-mobile__detail {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  min-height: 3rem;
}

.invoices-mobile__detail--amount {
  align-items: flex-end;
}

.invoices-mobile__detail--amount .invoices-row__amount {
  font-size: 0.9375rem;
  font-weight: 700;
}

.invoices-mobile__actions {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.75rem 1rem 1rem 1rem;
  border-top: 1px solid var(--glass-border);
  margin-top: 0.5rem;
}
</style>
