// src/app/(dashboard)/invoices/page.tsx
/**
 * Страница списка счетов (/invoices).
 *
 * Генерирует моковые счета через generateMockInvoices().
 * Фильтры: Все / К оплате / Оплаченные.
 * Каждый счёт — карточка с иконкой, номером, периодом, статусом и суммой.
 * Клик по счёту переходит на /invoices/[id] (детализация).
 */
'use client'

import { useState, useMemo } from 'react'
import Link from 'next/link'
import { UiCard } from '@/components/ui/ui-card'
import {
  type Invoice,
  type InvoiceStatus,
  formatInvoicePeriod,
  invoiceStatusLabels,
  invoiceStatusColors,
} from '@/types/invoice'
import { formatKopeks, formatDateShort } from '@/lib/formatters'
import { generateMockInvoices, UNPAID_STATUSES } from '@/lib/mock-invoices'

function getStatusBadgeClass(status: InvoiceStatus): string {
  if (UNPAID_STATUSES.includes(status)) return 'bg-red-500/20 text-red-400'
  const map: Record<string, string> = {
    gray: 'bg-gray-600/20 text-gray-400',
    primary: 'bg-primary/20 text-primary',
    blue: 'bg-blue-500/20 text-blue-400',
    green: 'bg-accent/20 text-accent',
    red: 'bg-red-500/20 text-red-400',
  }
  return map[invoiceStatusColors[status]] ?? map.gray
}

function DocumentIcon({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
    </svg>
  )
}
function CheckIcon({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  )
}
function ChevronRightIcon({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
    </svg>
  )
}

const filters = [
  { value: 'all' as const, label: 'Все' },
  { value: 'unpaid' as const, label: 'К оплате' },
  { value: 'paid' as const, label: 'Оплаченные' },
]

export default function InvoicesPage() {
  const [invoices] = useState<Invoice[]>(() => generateMockInvoices())
  const [filter, setFilter] = useState<'all' | 'unpaid' | 'paid'>('all')

  const filteredInvoices = useMemo(() => {
    if (filter === 'unpaid') return invoices.filter((inv) => UNPAID_STATUSES.includes(inv.status))
    if (filter === 'paid') return invoices.filter((inv) => inv.status === 'paid')
    return invoices
  }, [invoices, filter])

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-[var(--text-primary)]">Счета</h1>
        <p className="mt-1 text-[var(--text-muted)]">История выставленных счетов</p>
      </div>

      <div className="flex gap-2">
        {filters.map((f) => (
          <button
            key={f.value}
            type="button"
            onClick={() => setFilter(f.value)}
            className={`rounded-lg px-4 py-2 text-sm font-medium transition-colors ${
              filter === f.value ? 'bg-primary text-white' : 'text-[var(--text-muted)] hover:text-[var(--text-primary)]'
            }`}
            style={filter !== f.value ? { background: 'var(--glass-bg)' } : undefined}
          >
            {f.label}
          </button>
        ))}
      </div>

      <div className="space-y-4">
        {filteredInvoices.map((invoice) => (
          <Link key={invoice.id} href={`/invoices/${invoice.id}`}>
            <UiCard hover className="cursor-pointer">
              <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                <div className="flex items-start gap-4">
                  <div className="flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-primary/20 to-secondary/10">
                    {invoice.status === 'paid' ? (
                      <CheckIcon className="h-6 w-6 text-accent" />
                    ) : (
                      <DocumentIcon className="h-6 w-6 text-primary" />
                    )}
                  </div>
                  <div>
                    <div className="mb-1 flex items-center gap-2">
                      <span className="text-xs text-[var(--text-muted)]">{invoice.invoiceNumber}</span>
                      <span
                        className={`rounded px-2 py-0.5 text-xs font-medium ${getStatusBadgeClass(invoice.status)}`}
                      >
                        {invoiceStatusLabels[invoice.status]}
                      </span>
                    </div>
                    <p className="font-medium text-[var(--text-primary)]">{formatInvoicePeriod(invoice)}</p>
                    <div className="mt-2 flex items-center gap-3 text-xs text-[var(--text-muted)]">
                      {invoice.issuedAt && <span>Выставлен: {formatDateShort(invoice.issuedAt)}</span>}
                      {invoice.paidAt && <span>Оплачен: {formatDateShort(invoice.paidAt)}</span>}
                      {!invoice.paidAt && invoice.dueDate && (
                        <span>Срок: {formatDateShort(invoice.dueDate)}</span>
                      )}
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <span className="text-lg font-bold text-[var(--text-primary)]">
                    {formatKopeks(invoice.amount)}
                    <span className="text-sm font-normal text-[var(--text-muted)]"> ₽</span>
                  </span>
                  <ChevronRightIcon className="h-5 w-5 text-[var(--text-muted)]" />
                </div>
              </div>
            </UiCard>
          </Link>
        ))}

        {filteredInvoices.length === 0 && (
          <UiCard padding="lg">
            <p className="text-center text-[var(--text-muted)]">Счетов не найдено</p>
          </UiCard>
        )}
      </div>
    </div>
  )
}

// app/pages/invoices.vue
<script setup lang="ts">
/**
 * Страница счетов — история выставленных счетов:
 * - Фильтрация: все / к оплате / оплаченные
 * - Клик по счёту открывает его на invoice.doka.team
 *
 * Статусы счетов:
 * - pending, sent, viewed — неоплаченные
 * - paid — оплаченный
 * - expired — просроченный
 */
import type { InvoiceStatus } from '~/types/invoice'
import { invoiceStatusLabels, invoiceStatusColors, formatInvoicePeriod } from '~/types/invoice'
import { formatKopeks, formatDateShort } from '~/composables/useFormatters'

definePageMeta({
  middleware: 'auth'
})

// =============================================================================
// STORES & COMPOSABLES
// =============================================================================

const { fetchInvoices } = useInvoices()

// =============================================================================
// DATA — загрузка счетов
// =============================================================================

const { invoices, pending, error, refresh } = await fetchInvoices()

// =============================================================================
// STATE — фильтр
// =============================================================================

const filter = ref<'all' | 'unpaid' | 'paid'>('all')

// =============================================================================
// COMPUTED
// =============================================================================

// Отфильтрованный список счетов
const filteredInvoices = computed(() => {
  if (filter.value === 'unpaid') {
    return invoices.value.filter(inv => unpaidStatuses.includes(inv.status))
  }
  if (filter.value === 'paid') {
    return invoices.value.filter(inv => inv.status === 'paid')
  }
  return invoices.value
})

// =============================================================================
// CONSTANTS
// =============================================================================

// Статусы неоплаченных счетов
const unpaidStatuses = ['pending', 'sent', 'viewed', 'expired']

// Опции фильтра
const filters = [
  { value: 'all', label: 'Все' },
  { value: 'unpaid', label: 'К оплате' },
  { value: 'paid', label: 'Оплаченные' }
]

// =============================================================================
// METHODS
// =============================================================================

// Открыть счёт в новой вкладке (на invoice.doka.team)
function openInvoice(invoiceId: string): void {
  window.open(`https://invoice.doka.team/invoice/${invoiceId}`, '_blank')
}

// Получить CSS-класс для бейджа статуса
function getStatusBadgeClass(status: InvoiceStatus): string {
  const colorMap: Record<string, string> = {
    gray: 'bg-gray-600/20 text-gray-400',
    primary: 'bg-primary/20 text-primary',
    blue: 'bg-blue-500/20 text-blue-400',
    green: 'bg-accent/20 text-accent',
    red: 'bg-red-500/20 text-red-400'
  }
  return colorMap[invoiceStatusColors[status]] || colorMap.gray
}
</script>

<template>
  <div class="space-y-6">
    <!-- =====================================================================
         PAGE HEADER
         ===================================================================== -->
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
      <div>
        <h1 class="text-2xl font-bold text-[var(--text-primary)]">Счета</h1>
        <p class="text-[var(--text-muted)] mt-1">История выставленных счетов</p>
      </div>
    </div>

    <!-- =====================================================================
         FILTERS — фильтр по статусу оплаты
         ===================================================================== -->
    <div class="flex gap-2">
      <button
        v-for="f in filters"
        :key="f.value"
        @click="filter = f.value as any"
        class="px-4 py-2 rounded-lg text-sm font-medium transition-colors"
        :class="filter === f.value
          ? 'bg-primary text-white'
          : 'text-[var(--text-muted)] hover:text-[var(--text-primary)]'"
        :style="filter !== f.value ? 'background: var(--glass-bg);' : ''"
      >
        {{ f.label }}
      </button>
    </div>

    <!-- =====================================================================
         LOADING — скелетон загрузки
         ===================================================================== -->
    <div v-if="pending" class="space-y-4">
      <UiCard v-for="i in 3" :key="i" class="animate-pulse">
        <div class="flex items-center gap-4">
          <div class="w-12 h-12 rounded-xl bg-[var(--glass-bg)]"></div>
          <div class="flex-1 space-y-2">
            <div class="h-4 bg-[var(--glass-bg)] rounded w-1/3"></div>
            <div class="h-3 bg-[var(--glass-bg)] rounded w-1/2"></div>
          </div>
        </div>
      </UiCard>
    </div>

    <!-- =====================================================================
         ERROR — состояние ошибки
         ===================================================================== -->
    <UiCard v-else-if="error">
      <UiErrorState
        title="Ошибка загрузки"
        description="Не удалось загрузить счета"
        @retry="refresh"
      />
    </UiCard>

    <!-- =====================================================================
         INVOICES LIST — список счетов
         ===================================================================== -->
    <div v-else class="space-y-4">
      <UiCard
        v-for="invoice in filteredInvoices"
        :key="invoice.id"
        hover
        class="cursor-pointer"
        @click="openInvoice(invoice.id)"
      >
        <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div class="flex items-start gap-4">
            <div class="flex-shrink-0 w-12 h-12 rounded-xl bg-gradient-to-br from-primary/20 to-secondary/10 flex items-center justify-center">
              <Icon
                :name="invoice.status === 'paid' ? 'heroicons:check-circle' : 'heroicons:document-text'"
                class="w-6 h-6"
                :class="invoice.status === 'paid' ? 'text-accent' : 'text-primary'"
              />
            </div>
            <div>
              <div class="flex items-center gap-2 mb-1">
                <span class="text-xs text-[var(--text-muted)]">{{ invoice.invoiceNumber }}</span>
                <UiBadge :class="getStatusBadgeClass(invoice.status)" size="sm">
                  {{ invoiceStatusLabels[invoice.status] }}
                </UiBadge>
              </div>
              <p class="font-medium text-[var(--text-primary)]">{{ formatInvoicePeriod(invoice) }}</p>
              <div class="flex items-center gap-3 mt-2 text-xs text-[var(--text-muted)]">
                <span v-if="invoice.issuedAt">Выставлен: {{ formatDateShort(invoice.issuedAt) }}</span>
                <span v-if="invoice.paidAt">Оплачен: {{ formatDateShort(invoice.paidAt) }}</span>
                <span v-else-if="invoice.dueDate">Срок: {{ formatDateShort(invoice.dueDate) }}</span>
              </div>
            </div>
          </div>
          <div class="flex items-center gap-4">
            <span class="text-lg font-bold text-[var(--text-primary)]">
              {{ formatKopeks(invoice.amount) }}
              <span class="text-sm font-normal text-[var(--text-muted)]">₽</span>
            </span>
            <Icon name="heroicons:chevron-right" class="w-5 h-5 text-[var(--text-muted)] hidden sm:block" />
          </div>
        </div>
      </UiCard>

      <!-- Empty State -->
      <UiCard v-if="filteredInvoices.length === 0" padding="lg">
        <UiEmptyState
          icon="heroicons:document-text"
          title="Счетов не найдено"
        />
      </UiCard>
    </div>
  </div>
</template>
