// src/app/(dashboard)/profile/page.tsx
/**
 * @file Страница профиля (/profile).
 *
 * Отображает профиль пользователя с индикатором заполненности (progress bar)
 * и системой уровней: Новичок → Продвинутый → Эксперт → Мастер.
 *
 * Страница включает четыре информационных секции:
 * 1. Персональные данные (ProfilePersonalInfo).
 * 2. Контактная информация (ProfileContactInfo).
 * 3. Информация о договоре (ProfileContractInfo).
 * 4. Адрес (ProfileAddressInfo).
 *
 * Данные для отображения берутся из Zustand-сторов:
 * useUserStore (пользователь) и useAccountStore (аккаунт/договор).
 */
'use client'

import { useMemo } from 'react'
import { useUserStore } from '@/store/use-user-store'
import { ProfilePersonalInfo } from '@/components/profile/profile-personal-info'
import { ProfileContactInfo } from '@/components/profile/profile-contact-info'
import { ProfileContractInfo } from '@/components/profile/profile-contract-info'
import { ProfileAddressInfo } from '@/components/profile/profile-address-info'

const profileFields = [
  { name: 'Фото', filled: (u: { avatar?: string | null }) => !!u?.avatar, points: 10 },
  { name: 'Имя', filled: (u: { firstName?: string }) => !!u?.firstName, points: 10 },
  { name: 'Фамилия', filled: (u: { lastName?: string }) => !!u?.lastName, points: 10 },
  { name: 'Отчество', filled: (u: { middleName?: string }) => !!u?.middleName, points: 5 },
  { name: 'Дата рождения', filled: (u: { birthDate?: string | null }) => !!u?.birthDate, points: 10 },
  { name: 'Телефон', filled: (u: { phone?: string }) => !!u?.phone, points: 15 },
  { name: 'Email', filled: (u: { email?: string }) => !!u?.email, points: 15 },
  { name: 'Telegram', filled: (u: { telegramId?: string | null }) => !!u?.telegramId, points: 10 },
  { name: 'VK ID', filled: (u: { vkId?: string }) => !!u?.vkId, points: 15 },
]

function getLevelInfo(percent: number) {
  if (percent >= 100) return { level: 'Мастер', color: 'from-yellow-400 to-amber-500' }
  if (percent >= 80) return { level: 'Эксперт', color: 'from-purple-400 to-purple-600' }
  if (percent >= 50) return { level: 'Продвинутый', color: 'from-blue-400 to-blue-600' }
  return { level: 'Новичок', color: 'from-gray-400 to-gray-600' }
}

export default function ProfilePage() {
  const user = useUserStore((s) => s.user)
  const { completedPoints, totalPoints, percent, levelInfo } = useMemo(() => {
    const total = profileFields.reduce((s, f) => s + f.points, 0)
    const completed = profileFields
      .filter((f) => f.filled(user ?? {}))
      .reduce((s, f) => s + f.points, 0)
    const pct = total ? Math.round((completed / total) * 100) : 0
    return {
      completedPoints: completed,
      totalPoints: total,
      percent: pct,
      levelInfo: getLevelInfo(pct),
    }
  }, [user])

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-[var(--text-primary)]">Профиль</h1>
        <p className="mt-1 text-[var(--text-muted)]">Управление личными данными</p>
      </div>

      <div className="rounded-2xl p-4 md:p-6" style={{ background: 'var(--glass-bg)', border: '1px solid var(--glass-border)' }}>
        <div className="mb-2 flex items-center justify-between">
          <span className="text-sm font-medium text-[var(--text-primary)]">Заполненность профиля</span>
          <span className="text-sm text-[var(--text-muted)]">
            {completedPoints} / {totalPoints}
          </span>
        </div>
        <div className="h-2 overflow-hidden rounded-full" style={{ background: 'var(--glass-border)' }}>
          <div
            className={`h-full rounded-full bg-gradient-to-r ${levelInfo.color} transition-all duration-500`}
            style={{ width: `${percent}%` }}
          />
        </div>
        <p className="mt-2 text-xs text-[var(--text-muted)]">Уровень: {levelInfo.level}</p>
      </div>

      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
        <ProfilePersonalInfo />
        <ProfileContactInfo />
      </div>
      <ProfileContractInfo />
      <ProfileAddressInfo />
    </div>
  )
}

// app/pages/profile.vue
<script setup lang="ts">
/**
 * Страница профиля — объединённые данные:
 * - Персональные данные — ФИО, контакты, Telegram
 * - Договор — информация о договоре и адресе
 *
 * Особенности:
 * - Прогресс-бар заполненности профиля
 * - Уровни профиля (Новичок → Мастер)
 */
definePageMeta({
  middleware: 'auth'
})

// =============================================================================
// STORES
// =============================================================================

const userStore = useUserStore()

// =============================================================================
// STATE
// =============================================================================

const route = useRoute()

// Подсветка блока прогресса
const highlightProgress = ref(false)

// =============================================================================
// COMPUTED — прогресс заполнения профиля
// =============================================================================

// Поля профиля с весами (points)
const profileFields = computed(() => [
  { name: 'Фото', filled: !!userStore.user?.avatar, points: 10 },
  { name: 'Имя', filled: !!userStore.user?.firstName, points: 10 },
  { name: 'Фамилия', filled: !!userStore.user?.lastName, points: 10 },
  { name: 'Отчество', filled: !!userStore.user?.middleName, points: 5 },
  { name: 'Дата рождения', filled: !!userStore.user?.birthDate, points: 10 },
  { name: 'Телефон', filled: !!userStore.user?.phone, points: 15 },
  { name: 'Email', filled: !!userStore.user?.email, points: 15 },
  { name: 'Telegram', filled: !!userStore.user?.telegramId, points: 10 },
  { name: 'VK ID', filled: !!userStore.user?.vkId, points: 15 }
])

// Сумма заполненных полей
const completedPoints = computed(() =>
  profileFields.value.filter(f => f.filled).reduce((sum, f) => sum + f.points, 0)
)

// Максимальная сумма (100)
const totalPoints = computed(() =>
  profileFields.value.reduce((sum, f) => sum + f.points, 0)
)

// Процент заполнения
const completionPercent = computed(() =>
  Math.round((completedPoints.value / totalPoints.value) * 100)
)

// Незаполненные поля (для подсказки)
const missingFields = computed(() =>
  profileFields.value.filter(f => !f.filled)
)

// Уровень профиля (зависит от процента заполнения)
const levelInfo = computed(() => {
  const percent = completionPercent.value
  if (percent >= 100) return { level: 'Мастер', color: 'from-yellow-400 to-amber-500', icon: 'heroicons:star' }
  if (percent >= 80) return { level: 'Эксперт', color: 'from-purple-400 to-purple-600', icon: 'heroicons:academic-cap' }
  if (percent >= 50) return { level: 'Продвинутый', color: 'from-blue-400 to-blue-600', icon: 'heroicons:arrow-trending-up' }
  return { level: 'Новичок', color: 'from-gray-400 to-gray-600', icon: 'heroicons:user' }
})

// =============================================================================
// LIFECYCLE — обработка подсветки блока прогресса
// =============================================================================

// Проверка query параметра для подсветки
watch(() => route.query.highlight, (value) => {
  if (value === 'progress') {
    highlightProgress.value = true
    // Убираем подсветку через 0.7 секунды
    setTimeout(() => {
      highlightProgress.value = false
      // Очищаем query параметр
      navigateTo({ query: {} }, { replace: true })
    }, 700)
  }
}, { immediate: true })

// Проверка при монтировании
onMounted(() => {
  if (route.query.highlight === 'progress') {
    highlightProgress.value = true
    setTimeout(() => {
      highlightProgress.value = false
      navigateTo({ query: {} }, { replace: true })
    }, 700)
  }
})
</script>

<template>
  <div class="space-y-6">
    <!-- =====================================================================
         PAGE HEADER
         ===================================================================== -->
    <div>
      <h1 class="text-2xl font-bold text-[var(--text-primary)]">Профиль</h1>
      <p class="text-[var(--text-muted)] mt-1">Управление личными данными</p>
    </div>

    <!-- =====================================================================
         PROFILE CONTENT — объединённые данные профиля
         ===================================================================== -->
    <div class="space-y-6">
      <!-- Персональные данные и Контакты в ряд на десктопе -->
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <!-- Персональные данные -->
      <!-- ФИО, дата рождения -->
      <ProfilePersonalInfo />
        <!-- Телефон, email, Telegram -->
      <ProfileContactInfo />
    </div>

      <!-- Информация о договоре -->
      <ProfileContractInfo />
      <ProfileAddressInfo />
    </div>
  </div>
</template>
